branches:
    only:
    - develop
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
  global:
    - JULIA_DEBUG="all"
  matrix:
    - TRAVIS_JOB_TO_DO="RUNTESTS" COMPILED_MODULES="no"
    - TRAVIS_JOB_TO_DO="RUNTESTS" COMPILED_MODULES="yes"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[,B)" FORCE_DRY_RUN_ARGUMENT="FORCE_DRY_RUN"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[,B)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[B,C)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[C,D)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[D,Dn)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Dn,E)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[E,F)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[F,G)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[F,H)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[H,I)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[I,J)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[J,Ji)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Ji,Jt)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Jt,K)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[K,L)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[L,M)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[M,Mn)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Mn,N)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[N,O)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[O,P)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[P,Pn)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Pn,Q)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Q,R)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[R,S)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[S,Si)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Sq,Sx)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Sx,T)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[T,U)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[U,V)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[V,W)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[W,X)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[X,Y)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Y,Z)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[Z,a)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[a,g)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[g,n)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[n,t)"
    - GIT_DESTINATION_HOST="GITHUB" TASK="[t,)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[,B)" FORCE_DRY_RUN_ARGUMENT="FORCE_DRY_RUN"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[,B)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[B,C)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[C,D)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[D,Dn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Dn,E)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[E,F)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[F,G)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[G,H)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[H,I)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[I,J)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[J,Ji)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Ji,Jt)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Jt,K)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[K,L)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[L,M)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[M,Mn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Mn,N)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[N,O)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[O,P)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[P,Pn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Pn,Q)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Q,R)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[R,S)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[S,Si)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Si,Sq)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Sq,Sx)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Sx,T)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[T,U)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[U,V)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[V,W)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[W,X)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[X,Y)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Y,Z)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[Z,a)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[a,g)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[g,n)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[n,t)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="GITLAB" TASK="[t,)"
    - ALLOW_FAILURES="yes" ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[,B)" FORCE_DRY_RUN_ARGUMENT="FORCE_DRY_RUN"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[,B)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[B,C)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[C,D)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[D,Dn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Dn,E)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[E,F)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[F,G)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[G,H)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[H,I)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[I,J)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[J,Ji)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Ji,Jt)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Jt,K)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[K,L)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[L,M)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[M,Mn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Mn,N)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[N,O)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[O,P)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[P,Pn)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Pn,Q)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Q,R)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[R,S)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[S,Si)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Si,Sq)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Sq,Sx)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Sx,T)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[T,U)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[U,V)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[V,W)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[W,X)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[X,Y)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Y,Z)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[Z,a)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[a,g)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[g,n)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[n,t)"
    - ALLOW_FAILURES="yes" GIT_DESTINATION_HOST="BITBUCKET" TASK="[t,)"

git:
  depth: 99999999

julia:
  - "1.1"
language: julia
matrix:
  allow_failures:
    - env: ALLOW_FAILURES="yes"
  fast_finish: false
notifications:
  email:
    on_failure: always
    on_success: never
os:
  - linux

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - ./ci/travis/script.sh
after_script:
- true

############################################################################
